
name: Build Python Executable

on: [push]
  

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          pip install pyinstaller
      
      - name: Build executable
        run: pyinstaller --onefile --name WinProgramLister app.py
      
      - name: create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: Release v1
          overwrite: true
          body: |
            Release v1.0.0
          draft: false
          prerelease: false
      
      - name: Release
        uses: actions/upload-release-asset@v1
        with:
          #files: D:\a\WinProgramLister\WinProgramLister\dist\
          upload_url: ${{ steps.create_release.outputs.upload_url}}
          asset_path: dist\WinProgramLister.exe
          asset_name: WinProgramLister.exe
          asset_content_type: application/zip
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
