
name: Build Python Executable

on: [push]
  

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          pip install pyinstaller
      
      - name: Build executable
        run: pyinstaller --onefile --name WinProgramLister app.py
      - name: Listar conteúdo do diretório
        run: ls -la

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: 'release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
