name: Build and Release
on:
  push:
    tags:
      - 'v*.*.*' # Ajuste este padrão conforme necessário
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          
          pip install pyinstaller
      
      - name: Build executable
        run: pyinstaller --onefile --name winprogramlister app.py
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            
            winprogramlister.exe
        env:
          GITHUB_TOKEN: ${{ secrets.Token_winapp }}
